---
- hosts: Dev-Servers
  become: yes
  tasks:
  - name: Copy file with owner and permissions
    copy:
      src: /opt/test.txt
      dest: /tmp/test.txt
      owner: praveen
      group: praveen
      mode: '0755'
