---
- hosts: 
  become: yes

  vars_files:
   - aws_cred.yml #need to create one aws_cred.yml file and add accesskey and accesssecretkey 

  tasks:
   - name: aws s3 get operation
     aws_s3:
       aws_access_key: "{{ aws_access_key }}"
       aws_secret_key: "{{ aws_secret_key }}"
       bucket: <bucketname>
       object: <s3fileurl>
       dest: /tmp/
       mode: get
